### ISSUE TITLE
generator.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [ScreamCat1/angularCourses#7]
Если собирать приложение так 
ng build --prod. то будеи ошибка
Can't resolve all parameters for GeneratorService in D:/GitRepo/Home/Maksym_Pushkarov/src/app/core/services/generator.service.ts: (?). This will become an error in Angular v6.x

Если для GeneratorService используете декоратор @Injectable(), то параметрами конструктора не могут быть примитивы. Ангуляр считает, что это сервисы.

**Comment by ScreamCat1** [comment]
Убрал @Injectable()
